### ISSUE TITLE
height: inherit;display: inline-block; 冲突

### ISSUE THREAD

**Issue by 3344567** [kitwon/vue-loading-skeleton#11]
我看样式中使用的是height: inherit;但是同时又使用了display: inline-block;导致height无法顺利继承于parent;建议将height默认改成100%

**Comment by kitwon** [comment]
你好，`inline-block`和`height: inherit`应该可以继承上一级的高度的，或者方便的话可以提供一下以下用例我检查一下？

**Comment by kitwon** [comment]
Fell free to open.
