### ISSUE TITLE
How to change theme for global importing?

### ISSUE THREAD

**Issue by zhb124404** [kitwon/vue-loading-skeleton#20]
I use `<PuSkeletonTheme color="#00000" highlight="#ffffff" :duration="4"></PuSkeletonTheme>` but don't work.
who can provide a example，thanks.

**Comment by kitwon** [comment]
Click the story tabs in [storybook](https://kitwon.github.io/vue-loading-skeleton/?path=/story/skeleton-theme--change-theme), you can see all the demo code.

**Comment by maksakoviliya** [comment]
Looked, but did not find a solution. Can anybody help?
`import Skeleton from 'vue-loading-skeleton';
Vue.use(Skeleton)`

**Comment by kitwon** [comment]
> Looked, but did not find a solution. Can anybody help?
> `import Skeleton from 'vue-loading-skeleton'; Vue.use(Skeleton)`

Please provide more information about your issue.

**Comment by kitwon** [comment]
Fell free to open.
