### ISSUE TITLE
ERROR occurs when npm run build is triggered

### ISSUE THREAD

**Issue by fokosun** [kitwon/vue-loading-skeleton#24]
it worked fine in dev without any issues but when I try to deploy, specifically when npm run build is triggered, it throws an error:

`ERROR in static/js/vendor.953a63d9e24586dc640a.js from UglifyJs`
`Unexpected token: name (hook) [./~/vue-loading-skeleton/dist/vue-loading-skeleton.esm.js:177,0][static/js/vendor.953a63d9e24586dc640a.js:21495,8]`

The app is a vue cli app, the webpack config is:
```
module.exports = {
  // the main entry of our app
  entry: ['./src/main.js'],
  // output configuration
  output: {
    path: __dirname + '/build/',
    publicPath: 'build/',
    filename: 'build.js'
  },

  module: {
    loaders: [
      // process *.vue files using vue-loader
      { test: /\.vue$/, loader: 'vue' },
      // process *.js files using babel-loader
      // the exclude pattern is important so that we don't
      // apply babel transform to all the dependencies!
      { test: /\.js$/, loader: 'babel', exclude: /node_modules/ }
    ]
  },

  babel: {
    presets: ['es2015'],
    plugins: ['transform-runtime']
  }
}
```

Not sure how to resolve this. Any nodge in the right direction will be appreciated.

**Comment by kitwon** [comment]
This module will use esmodule if you use the `import` keyword,  and `UglifyJs` only work for es5.
So you can
* Use vue cli [transpiledependencies](https://cli.vuejs.org/config/#transpiledependencies) config.
* Use [terser](https://www.npmjs.com/package/terser-webpack-plugin) instead `UglifyJs`
