### ISSUE TITLE
Support Vuejs3

### ISSUE THREAD

**Issue by Catatomik** [kitwon/vue-loading-skeleton#27]
I tried to use this lib with Vuejs 3 and as excepted, it didn't work.
Any plan to update this for a Vuejs 3 (the composition API) compatibility ?

**Comment by Stormix** [comment]
+1 Let us know if you need help!

**Comment by kitwon** [comment]
This lib will support composition API in next 3 days.

**Comment by KayVeeCodes** [comment]
Any news about this?

**Comment by HelloAlexPan** [comment]
bump

**Comment by rzdev** [comment]
bump

**Comment by MeonisRP** [comment]
Does anyone know Vue 3 compatible loading placeholder? All of them are outdated, including this one

**Comment by smyja** [comment]
Bump

**Comment by kitwon** [comment]
Vue3 is supported!
Install with `yarn add vue-loading-skeleton@next`.

Report here if you find any bugs. 🤟
