### ISSUE TITLE
Border-radius

### ISSUE THREAD

**Issue by ferrthrash** [kitwon/vue-loading-skeleton#5]
Hello
Is a great component but need edit the style option "border-radius" to be perfect
thanks!!

**Comment by ferrthrash** [comment]
`<PuSkeleton v-else id="offerSkeleton" height="300px"/>


let childSkeleton = document.querySelector("#offerSkeleton").firstChild;
childSkeleton.style.borderRadius = "50px";
`
patch solution 😄

**Comment by kitwon** [comment]
Hello. Thanks for using this component. 😁
If you want to edit the child styles, add some style for the global class `pu-skeleton` maybe can fix your problem.
I will add more `props` to control the element style in next versions.

Thanks for your advising, Open anytime  :)
