### ISSUE TITLE
I got error in Nuxt.js project(typescript)

### ISSUE THREAD

**Issue by wowBlaBla** [kitwon/vue-loading-skeleton#51]
![image](https://user-images.githubusercontent.com/98627655/201487895-85b7a49a-4891-4843-bdea-f24aa31e1859.png)
![image](https://user-images.githubusercontent.com/98627655/201487910-f270c2d9-9598-4ffa-8045-a496f0c42a18.png)

**Comment by kitwon** [comment]
Maybe you can try `yarn install vue-loading-skeleton` instead of `vue-loading-skeleton@next`.
The **next** version is provided for Vue 3, but Nuxt.js is using Vue 2

**Comment by kitwon** [comment]
Feel free to open
