### ISSUE TITLE
Just only support JSX Template ??!

### ISSUE THREAD

**Issue by lizy0329** [kitwon/vue-loading-skeleton#6]
not work!

```
<template>
<Skeleton>
    {{dataSource.title}}
</Skeleton>
</template>

import Skeleton from 'vue-loading-skeleton';
components: {
        Skeleton
    }
```

**Comment by kitwon** [comment]
Hi, try replace `import Skeleton from 'vue-loading-skeleton';` to `import { Skeleton } from 'vue-loading-skeleton';` should be work 😀

**Comment by lizy0329** [comment]
import { Skeleton } from 'vue-loading-skeleton';

It's work for me! thank you
